export const ERROR = 'ERROR';

// USERS
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_REGISTRATION_REQUEST = 'USER_REGISTRATION_REQUEST';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const USER_DATA_FETCH_REQUEST = 'USER_DATA_FETCH_REQUEST';
export const USER_DATA_FETCH_SUCCESS = 'USER_DATA_FETCH_SUCCESS';
export const USER_DATA_FETCH_FAILURE = 'USER_DATA_FETCH_FAILURE';

// TOOLS/ITEMS
export const ITEMS_FETCH_REQUEST = 'ITEMS_FETCH_REQUEST';
export const ITEMS_FETCH_SUCCESS = 'ITEMS_FETCH_SUCCESS';
export const ITEMS_FETCH_FAILURE = 'ITEMS_FETCH_FAILURE';

export const ITEM_FETCH_REQUEST = 'ITEM_FETCH_REQUEST';
export const ITEM_FETCH_SUCCESS = 'ITEM_FETCH_SUCCESS';
export const ITEM_FETCH_FAILURE = 'ITEM_FETCH_FAILURE';